export const MOVIES = [
  { t: 'Dune', y: 2021, g: ['Sci-Fi', 'Action'], b: "A duke's son is thrown into a desert planet's war over a priceless resource." },
  { t: 'Dune: Part Two', y: 2024, g: ['Sci-Fi', 'Action'], b: 'The desert war escalates as prophecy and politics collide.' },
  { t: 'Arrival', y: 2016, g: ['Sci-Fi', 'Drama'], b: 'A linguist is recruited to talk to aliens before someone starts a war.' },
  { t: 'Interstellar', y: 2014, g: ['Sci-Fi', 'Drama'], b: 'A pilot leaves his kids behind to find humanity a new home.' },
  { t: 'Blade Runner 2049', y: 2017, g: ['Sci-Fi', 'Thriller'], b: 'A replicant hunter finds a secret that could unravel everything.' },
  { t: 'Blade Runner', y: 1982, g: ['Sci-Fi', 'Thriller'], b: "A detective hunts synthetic humans who don't want to be found." },
  { t: 'Ex Machina', y: 2014, g: ['Sci-Fi', 'Thriller'], b: 'A programmer tests whether an AI can truly think — and manipulate.' },
  { t: 'Children of Men', y: 2006, g: ['Sci-Fi', 'Thriller'], b: 'In a world with no new births, one pregnancy changes everything.' },
  { t: 'Annihilation', y: 2018, g: ['Sci-Fi', 'Horror'], b: 'A team enters a mutating zone that nothing has ever escaped.' },
  { t: 'District 9', y: 2009, g: ['Sci-Fi', 'Action'], b: 'An alien refugee crisis turns into a very personal transformation.' },
  { t: 'Looper', y: 2012, g: ['Sci-Fi', 'Action'], b: "A hitman's job is killing people sent back in time — including himself." },
  { t: 'Edge of Tomorrow', y: 2014, g: ['Sci-Fi', 'Action'], b: 'A soldier relives the same brutal invasion day over and over.' },
  { t: 'The Matrix', y: 1999, g: ['Sci-Fi', 'Action'], b: 'A hacker learns the world he knows is a simulation.' },
  { t: 'Minority Report', y: 2002, g: ['Sci-Fi', 'Thriller'], b: 'A cop who arrests future murderers becomes one himself.' },
  { t: 'Moon', y: 2009, g: ['Sci-Fi', 'Drama'], b: "A lone lunar worker discovers he isn't as alone as he thought." },
  { t: 'Primer', y: 2004, g: ['Sci-Fi', 'Indie'], b: 'Two engineers build a time machine in a garage and immediately regret it.' },
  { t: 'Snowpiercer', y: 2013, g: ['Sci-Fi', 'Action'], b: 'The last humans survive on a train, strictly divided by class.' },
  { t: 'Her', y: 2013, g: ['Sci-Fi', 'Romance'], b: 'A lonely writer falls for the AI running his operating system.' },
  { t: 'Everything Everywhere All at Once', y: 2022, g: ['Sci-Fi', 'Comedy'], b: 'A laundromat owner discovers she must save the multiverse — and her family.' },
  { t: 'Mad Max: Fury Road', y: 2015, g: ['Action', 'Sci-Fi'], b: 'A two-hour chase across the wasteland with almost no downtime.' },
  { t: 'John Wick', y: 2014, g: ['Action', 'Thriller'], b: "A retired hitman comes back for one very good reason: his dog." },
  { t: 'The Dark Knight', y: 2008, g: ['Action', 'Thriller'], b: 'A vigilante, a DA, and a clown redraw the moral map of a city.' },
  { t: 'Mission: Impossible - Fallout', y: 2018, g: ['Action', 'Thriller'], b: 'A recovered nuclear plot forces impossible choices under a ticking clock.' },
  { t: 'Die Hard', y: 1988, g: ['Action', 'Thriller'], b: "One cop, one skyscraper, one very bad Christmas Eve." },
  { t: 'Heat', y: 1995, g: ['Action', 'Drama'], b: 'A cop and a career criminal respect each other more than anyone else in their lives.' },
  { t: 'The Raid', y: 2011, g: ['Action'], b: 'A police raid on one building turns into a floor-by-floor fight for survival.' },
  { t: 'Baby Driver', y: 2017, g: ['Action', 'Indie'], b: "A getaway driver's job syncs every move to his own personal soundtrack." },
  { t: 'Top Gun: Maverick', y: 2022, g: ['Action', 'Drama'], b: 'An aging pilot trains a new generation for an impossible mission.' },
  { t: 'Speed', y: 1994, g: ['Action', 'Thriller'], b: 'A bus can’t slow below 50 mph or it explodes.' },
  { t: 'Kill Bill: Vol. 1', y: 2003, g: ['Action'], b: 'A former assassin works through a revenge list one name at a time.' },
  { t: 'The Bourne Identity', y: 2002, g: ['Action', 'Thriller'], b: "An amnesiac discovers his body remembers things his mind can't." },
  { t: 'Get Out', y: 2017, g: ['Horror', 'Thriller'], b: "A weekend meeting the in-laws turns into something far stranger." },
  { t: 'Hereditary', y: 2018, g: ['Horror', 'Drama'], b: 'A family inherits more from their late grandmother than they realize.' },
  { t: 'The Shining', y: 1980, g: ['Horror', 'Thriller'], b: "A family winters alone in a hotel that doesn't want them to leave." },
  { t: 'Alien', y: 1979, g: ['Horror', 'Sci-Fi'], b: 'A cargo crew picks up a signal, and something comes aboard with them.' },
  { t: 'A Quiet Place', y: 2018, g: ['Horror', 'Thriller'], b: 'A family survives by never making a sound — until they have to.' },
  { t: 'Midsommar', y: 2019, g: ['Horror', 'Drama'], b: "A grieving woman's trip to a remote festival turns ritualistic." },
  { t: 'The Babadook', y: 2014, g: ['Horror', 'Drama'], b: "A single mother's grief takes the shape of something in a children's book." },
  { t: 'It Follows', y: 2014, g: ['Horror', 'Indie'], b: 'A curse passes person to person, always walking, never stopping.' },
  { t: 'The Witch', y: 2015, g: ['Horror', 'Indie'], b: "A Puritan family's isolation curdles into paranoia and dread." },
  { t: 'Talk to Me', y: 2023, g: ['Horror'], b: 'A séance game using an embalmed hand goes exactly as badly as it sounds.' },
  { t: 'Barbarian', y: 2022, g: ['Horror', 'Thriller'], b: 'A double-booked Airbnb hides something much worse than an overbooking.' },
  { t: 'Sinister', y: 2012, g: ['Horror', 'Thriller'], b: "A true-crime writer finds home movies he wishes he hadn't." },
  { t: 'Superbad', y: 2007, g: ['Comedy'], b: "Two best friends try to make one last high school night count." },
  { t: 'Booksmart', y: 2019, g: ['Comedy', 'Indie'], b: 'Two overachievers try to cram four years of fun into one night.' },
  { t: 'Bridesmaids', y: 2011, g: ['Comedy', 'Romance'], b: "A maid of honor's life unravels right as her best friend's wedding ramps up." },
  { t: 'The Grand Budapest Hotel', y: 2014, g: ['Comedy', 'Drama'], b: 'A concierge and his protégé get tangled in a stolen painting and a fascist uprising.' },
  { t: 'Knives Out', y: 2019, g: ['Comedy', 'Thriller'], b: 'A detective sorts through a rich, awful family after the patriarch dies.' },
  { t: 'Napoleon Dynamite', y: 2004, g: ['Comedy', 'Indie'], b: 'An awkward teen navigates small-town Idaho, one deadpan moment at a time.' },
  { t: 'The Big Lebowski', y: 1998, g: ['Comedy'], b: 'A ruined rug sends a laid-back bowler into a kidnapping plot he never wanted.' },
  { t: 'Groundhog Day', y: 1993, g: ['Comedy', 'Romance'], b: 'A cynical weatherman relives the same small-town day until he gets it right.' },
  { t: 'What We Do in the Shadows', y: 2014, g: ['Comedy', 'Horror'], b: 'Vampire roommates document their extremely mundane undead lives.' },
  { t: 'Paddington 2', y: 2017, g: ['Comedy'], b: 'A polite bear is framed for theft and has to clear his name from prison.' },
  { t: 'The Nice Guys', y: 2016, g: ['Comedy', 'Action'], b: 'A washed-up PI and a hired muscle stumble into a conspiracy neither wanted.' },
  { t: 'Palm Springs', y: 2020, g: ['Comedy', 'Sci-Fi'], b: 'Two wedding guests get stuck reliving the same day together.' },
  { t: 'Moonlight', y: 2016, g: ['Drama', 'Indie'], b: 'Three chapters of one man’s life, told in silence and light.' },
  { t: 'The Social Network', y: 2010, g: ['Drama'], b: 'A dorm-room project ends in billions and zero friends kept.' },
  { t: 'Whiplash', y: 2014, g: ['Drama', 'Indie'], b: 'A drummer and his instructor push each other well past reasonable.' },
  { t: 'Manchester by the Sea', y: 2016, g: ['Drama'], b: "A man returns home to raise his nephew and face what he's been avoiding." },
  { t: 'Little Women', y: 2019, g: ['Drama', 'Romance'], b: 'Four sisters grow up, fall in and out of step, and chase their own paths.' },
  { t: 'The Florida Project', y: 2017, g: ['Drama', 'Indie'], b: "A six-year-old's summer unfolds in the shadow of Disney World's motels." },
  { t: 'Nomadland', y: 2020, g: ['Drama', 'Indie'], b: 'A woman takes to the road after her town, and her old life, disappear.' },
  { t: '12 Years a Slave', y: 2013, g: ['Drama'], b: 'A free man is kidnapped into slavery and fights to survive and be believed.' },
  { t: 'There Will Be Blood', y: 2007, g: ['Drama'], b: "An oil prospector's ambition curdles into something monstrous." },
  { t: 'No Country for Old Men', y: 2007, g: ['Drama', 'Thriller'], b: 'A hunter finds drug money in the desert, and a killer finds him.' },
  { t: 'The Departed', y: 2006, g: ['Drama', 'Thriller'], b: 'A cop and a criminal go undercover on opposite sides of the same gang.' },
  { t: 'La La Land', y: 2016, g: ['Romance', 'Drama'], b: 'A pianist and an actress fall for each other while chasing separate dreams.' },
  { t: 'Amélie', y: 2001, g: ['Romance', 'Comedy'], b: "A shy waitress starts secretly fixing strangers' lives in Montmartre." },
  { t: 'Pride & Prejudice', y: 2005, g: ['Romance', 'Drama'], b: 'Two proud, stubborn people slowly realize they were wrong about each other.' },
  { t: 'Portrait of a Lady on Fire', y: 2019, g: ['Romance', 'Indie'], b: 'A painter and her subject fall for each other on an isolated island.' },
  { t: 'Crazy Rich Asians', y: 2018, g: ['Romance', 'Comedy'], b: "A meet-the-parents trip reveals her boyfriend's family is absurdly wealthy." },
  { t: 'Eternal Sunshine of the Spotless Mind', y: 2004, g: ['Romance', 'Sci-Fi'], b: 'A breakup leads two people to erase each other from memory — badly.' },
  { t: 'Before Sunrise', y: 1995, g: ['Romance', 'Drama'], b: 'Two strangers get off a train in Vienna and talk until sunrise.' },
  { t: 'Call Me by Your Name', y: 2017, g: ['Romance', 'Drama'], b: "A summer in Italy becomes the defining season of a young man's life." },
  { t: 'The Notebook', y: 2004, g: ['Romance', 'Drama'], b: 'A summer romance is tested by class, war, and years apart.' },
  { t: 'About Time', y: 2013, g: ['Romance', 'Sci-Fi'], b: 'A young man who can time-travel learns what actually matters to fix.' },
  { t: 'Little Miss Sunshine', y: 2006, g: ['Indie', 'Comedy'], b: 'A broken-down family van races cross-country for a kids’ pageant.' },
  { t: 'Lady Bird', y: 2017, g: ['Indie', 'Drama'], b: 'A senior year of fights, friendships, and figuring out who you want to be.' },
  { t: 'Juno', y: 2007, g: ['Indie', 'Comedy'], b: 'A sharp-tongued teenager navigates an unplanned pregnancy on her own terms.' },
  { t: 'Swiss Army Man', y: 2016, g: ['Indie', 'Comedy'], b: 'A stranded man befriends a very unusual, very dead new friend.' },
  { t: 'Moonrise Kingdom', y: 2012, g: ['Indie', 'Romance'], b: 'Two twelve-year-olds run away together into the New England woods.' },
  { t: 'Frances Ha', y: 2012, g: ['Indie', 'Comedy'], b: "A dancer in her late twenties tries to figure out an actual plan." },
  { t: 'Past Lives', y: 2023, g: ['Indie', 'Romance'], b: 'Childhood friends reconnect decades later, each with a different life now.' },
  { t: 'Minari', y: 2020, g: ['Indie', 'Drama'], b: 'A Korean-American family tries to build a farm and a future in Arkansas.' },
  { t: 'CODA', y: 2021, g: ['Indie', 'Drama'], b: 'The only hearing member of a Deaf family discovers she can sing.' },
  { t: 'Zodiac', y: 2007, g: ['Thriller'], b: "A cartoonist gets obsessed with a killer the police can't catch." },
  { t: 'Prisoners', y: 2013, g: ['Thriller', 'Drama'], b: 'A father takes the search for his missing daughter into his own hands.' },
  { t: 'Gone Girl', y: 2014, g: ['Thriller', 'Drama'], b: "A marriage's cracks become a nationwide media spectacle overnight." },
  { t: 'Se7en', y: 1995, g: ['Thriller', 'Horror'], b: 'Two detectives track a killer staging murders around the seven deadly sins.' },
  { t: 'Nightcrawler', y: 2014, g: ['Thriller', 'Drama'], b: "A man builds a career filming the worst nights of other people's lives." },
  { t: 'Parasite', y: 2019, g: ['Thriller', 'Drama'], b: 'A family cons their way into a wealthy household, until the house fights back.' },
  { t: 'The Silence of the Lambs', y: 1991, g: ['Thriller', 'Horror'], b: 'A trainee agent trades information with an imprisoned killer to catch another.' },
  { t: 'Shutter Island', y: 2010, g: ['Thriller'], b: 'A marshal investigating an asylum starts to doubt his own case.' },
  { t: 'Spirited Away', y: 2001, g: ['Fantasy', 'Indie'], b: 'A girl works in a bathhouse for spirits to save her transformed parents.' },
  { t: 'Coco', y: 2017, g: ['Fantasy', 'Comedy'], b: 'A boy crosses into the Land of the Dead to find his musician great-great-grandfather.' },
  { t: 'The Princess Bride', y: 1987, g: ['Fantasy', 'Romance'], b: 'True love, a Sicilian, and a fire swamp — read to you by grandpa.' },
  { t: 'Pan’s Labyrinth', y: 2006, g: ['Fantasy', 'Drama'], b: 'A girl escapes wartime Spain into a labyrinth with rules of its own.' },
  { t: 'Good Will Hunting', y: 1997, g: ['Drama', 'Indie'], b: "A janitor's genius gets discovered, and so does everything he's been avoiding." },
  { t: 'The Prestige', y: 2006, g: ['Thriller', 'Sci-Fi'], b: 'Two rival magicians escalate a trick war well past the point of sanity.' },
  { t: 'Inception', y: 2010, g: ['Sci-Fi', 'Thriller'], b: "A team plants an idea in someone's mind across four layers of dreams." },
]
